import type { ArenaSurvivorEnemyDefinition } from "./types.js";

export const arenaSurvivorEnemyDefinitions = [
  {
    id: "slime-blob",
    displayName: "Slime Blob",
    role: "chaser",
    tags: [
      "starter",
      "swarm",
      "basic",
    ],
    baseDescription: "Langsamer Grundgegner fuer die fruehen Wellen.",
    minWave: 1,
    spawnWeight: 12.7,
    radius: 14,
    maxHp: 27,
    moveSpeed: 126,
    contactDamage: 14,
    contactDamageCooldownMs: 450,
    spritePath: "/arena-survivor/enemies/sprites/slime-blob.svg",
    portraitPath: "/arena-survivor/enemies/portraits/slime-blob.svg",
  },
  {
    id: "fang-crawler",
    displayName: "Fang Crawler",
    role: "chaser",
    tags: [
      "fast",
      "pressure",
      "hunter",
    ],
    baseDescription: "Schneller Nahkaempfer, der den Spieler hart verfolgt.",
    minWave: 3,
    spawnWeight: 10.2,
    radius: 15,
    maxHp: 27,
    moveSpeed: 167,
    contactDamage: 15,
    contactDamageCooldownMs: 380,
    spritePath: "/arena-survivor/enemies/sprites/fang-crawler.svg",
    portraitPath: "/arena-survivor/enemies/portraits/fang-crawler.svg",
  },
  {
    id: "stone-brute",
    displayName: "Stone Brute",
    role: "brute",
    tags: [
      "tank",
      "heavy",
      "slow",
    ],
    baseDescription: "Langsam, robust und mit hohem Kontaktschaden.",
    minWave: 7,
    spawnWeight: 6.6,
    radius: 22,
    maxHp: 126,
    moveSpeed: 104,
    contactDamage: 22,
    contactDamageCooldownMs: 560,
    spritePath: "/arena-survivor/enemies/sprites/stone-brute.svg",
    portraitPath: "/arena-survivor/enemies/portraits/stone-brute.svg",
  },
  {
    id: "ember-wisp",
    displayName: "Ember Wisp",
    role: "shooter",
    tags: [
      "ranged",
      "fire",
      "pressure",
    ],
    baseDescription: "Leichter Distanzgegner, der Feuerbolzen auf den Spieler schiesst.",
    minWave: 4,
    spawnWeight: 8,
    radius: 13,
    maxHp: 32,
    moveSpeed: 134,
    contactDamage: 12,
    contactDamageCooldownMs: 600,
    shootCooldownMs: 1438,
    shootRange: 310,
    projectile: {
      id: "ember-bolt",
      radius: 6,
      speed: 330,
      damage: 17,
      lifetimeMs: 2400,
      maxRange: 380,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/ember-wisp.svg",
    portraitPath: "/arena-survivor/enemies/portraits/ember-wisp.svg",
  },
  {
    id: "toxic-shroom",
    displayName: "Toxic Shroom",
    role: "shooter",
    tags: [
      "ranged",
      "poison",
      "area",
    ],
    baseDescription: "Gefaehrlicher Distanzgegner mit langsamen Giftsporen.",
    minWave: 8,
    spawnWeight: 6.6,
    radius: 16,
    maxHp: 61,
    moveSpeed: 98,
    contactDamage: 13,
    contactDamageCooldownMs: 650,
    shootCooldownMs: 2125,
    shootRange: 340,
    projectile: {
      id: "toxic-spore",
      radius: 7,
      speed: 275,
      damage: 14,
      lifetimeMs: 2600,
      maxRange: 420,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/toxic-shroom.svg",
    portraitPath: "/arena-survivor/enemies/portraits/toxic-shroom.svg",
  },
  {
    id: "scrap-goliath",
    displayName: "Scrap Goliath",
    role: "brute",
    tags: [
      "boss",
      "mini-boss",
      "heavy",
      "metal",
    ],
    baseDescription: "Ein massiver Mini-Boss, der einmalig in Welle 10 auf das Team losgeht.",
    minWave: 10,
    spawnWeight: 0,
    radius: 45,
    maxHp: 1500,
    moveSpeed: 92,
    contactDamage: 28,
    contactDamageCooldownMs: 430,
    spritePath: "/arena-survivor/enemies/sprites/scrap-goliath.svg",
    portraitPath: "/arena-survivor/enemies/portraits/scrap-goliath.svg",
  },
  {
    id: "crimson-overlord",
    displayName: "Crimson Overlord",
    role: "shooter",
    tags: [
      "boss",
      "ranged",
      "radial",
      "crimson",
    ],
    baseDescription: "Der Welle-20-Boss entfesselt alle 5 Sekunden einen Ring aus roten Kugeln.",
    minWave: 20,
    spawnWeight: 0,
    radius: 60,
    maxHp: 5000,
    moveSpeed: 74,
    contactDamage: 34,
    contactDamageCooldownMs: 520,
    shootCooldownMs: 5000,
    shootRange: 460,
    projectile: {
      id: "crimson-orb",
      radius: 10,
      speed: 280,
      damage: 18,
      lifetimeMs: 3200,
      maxRange: 640,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/crimson-overlord.svg",
    portraitPath: "/arena-survivor/enemies/portraits/crimson-overlord.svg",
  },
] as const satisfies readonly ArenaSurvivorEnemyDefinition[];

export const arenaSurvivorEnemyDefinitionsById = Object.fromEntries(
  arenaSurvivorEnemyDefinitions.map((enemy) => [enemy.id, enemy])
) satisfies Record<string, ArenaSurvivorEnemyDefinition>;
